name: Manage Pull Request
on: [push]

jobs:
  gif:
    name: Find a funny Gif
    runs-on: ubuntu-latest
    steps:

      - name: Test
        run: echo 'The result was ${{ steps.giphy_url.outputs.url }}'
  pr:
    name: Create/Update the PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install hub
        uses: geertvdc/setup-hub@master
      - name: Get a random GIF url
        shell: bash
        id: giphy_url
        env:
          API_KEY: ${{ secrets.GIPHY_API_KEY }}
        run: |
          SEARCH="failure"
          URL=$(curl -s https://api.giphy.com/v1/gifs/random\?api_key\=${API_KEY}\&tag\=${SEARCH} | jq .data.url | tr -d \")
          echo "::set-output name=url::${URL}"
      - name:  Create a PR if it does not exists
        shell: bash
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -la
          PR_TITLE="test title"
          PR_DESC="![GIF](${{ steps.giphy_url.outputs.url }})
          <hr />

          <ul><li>one</li></ul>"
          MESSAGE="${PR_TITLE}

          ${PR_DESC}"
          hub pull-request -b master -m "${MESSAGE}" || true
